version: "3.9"
volumes:
  dbpg:
networks:
  postgres:
    driver: bridge
services:
  db:
    image: postgres:latest
    volumes:
      - dbpg:/usr/app
    restart: always
    ports:
      - "5432:5432"
    networks:
        - postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $TYPEORM_PASSWORD
      POSTGRES_USER: $TYPEORM_USERNAME
      POSTGRES_DB: $TYPEORM_DATABASE
      POSTGRES_HOST: $TYPEORM_HOST
      #DATABASE_URL: "postgres://postgres:docker@postgres:5432/warren_db"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app_node:
    depends_on:
        - db
    build:  .
    command: yarn dev:server
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app/db
    networks:
        - postgres



